spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.233.42:3306/ezheli?useUnicode=true&characterEncoding=utf-8
    username: heydon
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.heydon.ezheli.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8088
